[Application]
FileLogger\Age=1
FileLogger\AgeType=1
FileLogger\Backup=true
FileLogger\DeleteOld=true
FileLogger\Enabled=true
FileLogger\MaxSizeBytes=66560
FileLogger\Path=/home/runner/.local/share/qBittorrent/logs

[BitTorrent]
Session\ExcludedFileNames=
Session\Port=57492
Session\QueueingSystemEnabled=false

[Core]
AutoDeleteAddedTorrentFile=Never

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=6

[Preferences]
General\Locale=en
MailNotification\req_auth=true
WebUI\AuthSubnetWhitelist=@Invalid()
WebUI\LocalHostAuth=false
WebUI\Password_PBKDF2="@ByteArray(Aa+Exg5CUNyv3jXOKa7BKw==:P0F8un0425JfwrTHopWlB28XdT7RHPMUsK0qHPC+6C8o3nMlaZtJj9q+0g10jwk13gySqLF1XzVsKFwB+OnxgQ==)"

[RSS]
AutoDownloader\DownloadRepacks=true
AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
