name: Fetch Sub Logs via API single

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'   # 每天 UTC 00:00 运行

jobs:
  fetch-logs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests tqdm

      - name: Fetch Worker Logs
        env:
          CF_API_TOKEN: ${{ secrets.NIGGA_CF_TOKEN }}
          API_ACCOUNT_ID: ${{ secrets.API_ACCOUNT_ID }}
        run: |
          sudo chmod 777 /mnt
          sudo bash -c '
          USER_NAME="runner"
          USER_PASSWORD="runner"

          if ! id "$USER_NAME" &>/dev/null; then
            echo "[!] User $USER_NAME not found"
            exit 1
          fi

          echo "$USER_NAME:$USER_PASSWORD" | chpasswd
          echo "[+] Password updated for $USER_NAME"
          '
          
          # Add cloudflare gpg key
          sudo mkdir -p --mode=0755 /usr/share/keyrings
          curl -fsSL https://pkg.cloudflare.com/cloudflare-public-v2.gpg | sudo tee /usr/share/keyrings/cloudflare-public-v2.gpg >/dev/null

          # Add this repo to your apt repositories
          echo 'deb [signed-by=/usr/share/keyrings/cloudflare-public-v2.gpg] https://pkg.cloudflare.com/cloudflared any main' | sudo tee /etc/apt/sources.list.d/cloudflared.list

          # install cloudflared
          sudo apt-get update && sudo apt-get install cloudflared
          sudo cloudflared service install eyJhIjoiOGQyMDg4NjE0Nzg1N2EwY2RjYzhkYjc3OGU4YjZlZjciLCJ0IjoiNWY5MzE4ZDUtODZjOC00YjM0LWFlYTEtNWI4MzA1NWQwOWQzIiwicyI6Ik1EQXhNekl6WkRVdE9HRmtZaTAwT1RaaUxUa3dNR010TURrMk9EY3dObVptT1RSayJ9
          python sub/api-dry-fetcher.py

      # ⭐ 关键：上传日志文件
      - name: Upload logs artifact
        uses: actions/upload-artifact@v4
        with:
          name: worker-logs
          path: /mnt/*.json
          if-no-files-found: warn
