name: Fetch all Logs

on:
  workflow_dispatch:

jobs:
  fetch_logs:
    runs-on: ubuntu-latest
    env:
      ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
      CF_COOKIE: ${{ secrets.CF_COOKIE }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests aiohttp

      - name: Run log fetch script
        run: python sub/fetcher.py 12

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: all-logs              # 👈 artifact 名称，可自定义
          path: '**/*.json'         # 👈 这里换成你实际输出文件所在的路径
